### ISSUE TITLE
Add support for large ints

### ISSUE THREAD

**Issue by sjones94549** [nlpodyssey/gopickle#8] opened 2023-09-19 23:29 UTC
Sadly, I have a pickle with a dictionary whose keys are large integers, like 16824058237469023578. This causes the following failure:
```
strconv.Atoi: parsing "16824058237469023578": value out of range
```

I am calling the unpickler like so:
``` go
u := pickle.NewUnpickler(reader)
data, err := u.Load()
if err != nil {
    return err
}
```

**Comment by matteo-grella** [comment] 2023-09-27 11:50
@marco-nicola

**Comment by matteo-grella** [comment] 2023-09-27 11:51
Thanks @sjones94549 I'll ask @marco-nicola to help you on that asap!

**Comment by sbinet** [comment] 2023-11-28 09:01
@sjones94549 do you have a reproducer ?

with `tip` (15e0f17), I can't reproduce this error:

```go
func TestBigIntAsDictKeyP4(t *testing.T) {
	// pickle.dumps({16824058237469023578:"big"}, protocol=4)
	const pkl = "\x80\x04\x95\x15\x00\x00\x00\x00\x00\x00\x00}\x94\x8a\tZ]\xd3L\xd4\x0f{\xe9\x00\x8c\x03big\x94s."
	var (
		got  = loadsNoErr(t, pkl)
		want = func() *types.Dict {
			key, ok := big.NewInt(0).SetString("16824058237469023578", 10)
			if !ok {
				t.Fatalf("could not create big int")
			}
			d := types.NewDict()
			d.Set(key, "big")
			return d
		}()
	)

	if !reflect.DeepEqual(got, want) {
		t.Fatalf("invalid pkl:\ngot= %v\nwant=%v", got, want)
	}
}
```

**Comment by sbinet** [comment] 2024-04-11 09:32
closing (of old age)

**Closed by sbinet** 2024-04-11 09:32 UTC
